### POPULATE DATABASE WITH TRIPS AND GUIDES
POST {{url}}/trips/populate
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

### GET ALL TRIPS
GET {{url}}/trips
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

### GET TRIP BY ID
GET {{url}}/trips/4
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

### CREATE A TRIP
POST {{url}}/trips
Content-Type: application/json
Authorization: Bearer {{jwt_token}}


{
  "name": "Mountain Hike",
  "starttime": "2024-05-01T09:00:00",
  "endtime": "2024-05-01T17:00:00",
  "longitude": -105.2705,
  "latitude": 40.0150,
  "price": 250.0,
  "category": "SNOW"
}

### UPDATE A TRIP
PUT {{url}}/trips/3
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "name": "Updated Mountain Hike",
  "starttime": "2024-05-01T09:00:00",
  "endtime": "2024-05-01T18:00:00",
  "longitude": -105.2705,
  "latitude": 40.0150,
  "price": 275.0,
  "category": "LAKE"
}

### DELETE A TRIP
DELETE {{url}}/trips/2
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

### ADD AN EXISTING GUIDE TO A TRIP
PUT {{url}}/trips/10/guides/4
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

### FILTER TRIPS BY CATEGORY
GET {{url}}/trips/category/SNOW
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

### GET TOTAL PRICE OF TRIPS BY GUIDE
GET {{url}}/trips/guides/totalprice
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

### GET TOTAL PACKING WEIGHT FOR A TRIP
GET {{url}}/trips/4/packing-weight
Content-Type: application/json
Authorization: Bearer {{jwt_token}}









### Create a new user - this one will only get a USER role by default
POST {{url}}/auth/register/

{
    "username": "testuser",
    "password": "test123"
}

###
POST {{url}}/auth/login/

{
    "username": "testuser",
    "password": "test123"
}

> {%
    client.global.set("jwt_token", response.body.token);
    console.log("JWT Token:", client.global.get("jwt_token"));
%}

###
GET {{url}}/protected/user_demo/
Accept: application/json
Authorization: Bearer {{jwt_token}}


###
GET {{url}}/protected/admin_demo/
Accept: application/json
Authorization: Bearer {{jwt_token}}


### Add admin role to user
POST {{url}}/auth/user/addrole/
Accept: application/json
Authorization: Bearer {{jwt_token}}

{
    "role": "admin"
}
Accept: application/json
Authorization: Bearer {{jwt_token}}

### Reset token
GET {{url}}/auth/test/

> {%
    client.global.set("jwt_token", null);
    console.log("JWT Token:", client.global.get("jwt_token"));
%}

